### ISSUE TITLE
Rename ROOT as root

### ISSUE THREAD

**Issue by Salamandar** [stefanocampanella/ROOT#1]
Hi there,
the AUR package is named root (no caps) and your package is ROOT (caps lock). You should rename your package… Because of file conflicts when installing this thinking it will only be an update.

**Comment by stefanocampanella** [comment]
Hi!
this pkgbuild wasn't meant to be a replacement of the one on the AUR and, being the software called ROOT, I thought that the uppercase one was a proper name for the package. However the [Arch packaging standards](https://wiki.archlinux.org/index.php/Arch_packaging_standards#Package_etiquette) warns that pkgnames should be lowercase, therefore I will change the `pkgname` (and remove the `provides`)
