### ISSUE TITLE
cmake fails because capital package name dosn't correspond to lowercase tarball name

### ISSUE THREAD

**Issue by meliache** [stefanocampanella/ROOT#2]
With the original package build I got an error message that `src/ROOT-6.06.00` does not exist (`$pkgname-$pkgver`), which seems because the actual tarball from the source and thus the directory have "root" written in  lower case: `ftp://root.cern.ch/root/root_v${pkgver}.source.tar.gz"`. Because of that `cmake -C $srcdir/settings.cmake $srcdir/$_pkgid` failed. I fixed it for me by changing the package name into lower case.

**Comment by stefanocampanella** [comment]
Oops! My fault. Everything should be fine now.
